### ISSUE TITLE
Using untrusted Task's results in the trusted artifact chain should be a violation

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1012]
The policy rules in the `policy.release.trusted_task` should prohibit the use of results from an untrusted Task in the chain of Tasks formed by examining the Trusted Artifact breadcrumbs. Using input from untrusted Task could lead to compromises of the build pipeline.

**Comment by lcarva** [comment]
Can you clarify the issue? I have verified that untrusting a Task in the chain does trigger a violation.

**Comment by zregvart** [comment]
The issue is that an a Task in the chain of all trusted Tasks could still use a result from an untrusted Task outside of the chain. For example the `build-image-manifest` Task could rely on results from trusted and untrusted Tasks.

**Comment by lcarva** [comment]
Right. That sounds like exactly what I tested which is passing. Can you provide a reproducer?

Are you talking about just the `_ARTIFACT` results? Or any result in general?

**Comment by zregvart** [comment]
**Any result**, for example the `build-image-manifest` is not using any `*_ARTIFACT` results [here](https://github.com/enterprise-contract/golden-container/blob/71932a9ce8c88d59112d281392a3275e5328f24d/.tekton/golden-container-push.yaml#L294-L295).
_Any_ input to the Task on the trusted chain _must_ originate from a trusted task.

**Comment by lcarva** [comment]
The tricky part here will be detecting if a certain parameter was populated from the results of another Task (vs just a hard-coded value, for example). Although that's obvious from the Pipeline definition, the SLSA Provenance contains the resolved values.

We can  take a similar approach as we have done for the `*_ARTIFACT` parameter, but doing this for every parameter requires special attention.

**Comment by lcarva** [comment]
I think we may need to handle this on a case-by-case basis. The `build-image-manifest` example provided above is actually really interesting.

The PipelineTask, provides three parameters to the Task:

* `IMAGE`. This is mapped to the Pipeline parameter `output-image`. It specifies where the Image Index will be pushed to.
* `COMMIT_SHA`. Mapped from the `commit` result of the `clone-repository` PipelineTask. (I think this is a leftover parameter, but for this argument, let's pretend it's a perfectly valid and useful parameter.)
* `IMAGES`. As mentioned earlier, it's a list of Image Manifest that were built by previous Tasks.

Ideally, I think we want the following behavior:

* `IMAGE`. No validation required. This is a user provided parameter for where the image will be pushed to.
* `COMMIT_SHA`. Validate that its value comes from the result of a trusted Task, particularly from the `git-clone` Task.
* `IMAGES`. Validate each value comes from the result of a trusted Task, particularly one of the `buildah` Tasks.

Another example is the [build-source-image](https://github.com/enterprise-contract/golden-container/blob/71932a9ce8c88d59112d281392a3275e5328f24d/.tekton/golden-container-push.yaml#L313-L341). Notably, the `BASE_IMAGES` should come from a trusted Task.

I'll make an initial implementation that does treat these things on a case-by-case basis. If anything, maybe this will help us surface a generic pattern.

NOTE: There are other variations of this, for example [clamav-scan](https://github.com/enterprise-contract/golden-container/blob/71932a9ce8c88d59112d281392a3275e5328f24d/.tekton/golden-container-push.yaml#L408-L429). There we want the `image-digest` and the `image-url` to come from results of a trusted Task. I suppose that validation is not needed there because the Task will emit the [IMAGES_PROCESSED](https://github.com/konflux-ci/architecture/blob/main/ADR/0030-tekton-results-naming-convention.md#tekton-result-format-for-images_processed) result which we can cross reference with the builder trusted Tasks. If the user provides a bogus image ref, it should be easily detected. This falls more into the territory of EC-652 since `clamav-scan` is not a builder Task.

**Comment by zregvart** [comment]
I think we can match on the parameter values, and I'm a bit wary of introducing special handling per parameter. Here's how I would try to tackle that: gather all parameter values given to a Task on the trusted section of the pipeline, gather all parameters passed to the pipeline and all results emitted from the tasks on the trusted section, check if we're left with something when the each of the results is removed from the parameters. The removal could be something like `replace(param_value, result_value, "")`, then the check could be that the resulting set of all Task parameters with all the Pipeline parameters and all results from the trusted section is trivial; with trivial being one (two?) characters long.

Yes, I think we should focus only on the trusted section of the Pipeline, I don't think we care what parameter was passed to the `clamav-scan`, we have other checks for that.

**Comment by lcarva** [comment]
Must also take into account default parameter values. We cannot distinguish those in the SLSA Provenance. For example, here's what's reported from the buildah Task:

```
🐚 < att.json jq '.predicate.buildConfig.tasks[] | select(.name == "build-container-amd64") | .invocation.parameters'
{
  "BUILDER_IMAGE": "",
  "BUILD_ARGS": [],
  "BUILD_ARGS_FILE": "",
  "COMMIT_SHA": "530e8bd12585a3668f2af10454041738cb076883",
  "CONTEXT": ".",
  "DOCKERFILE": "Containerfile",
  "DOCKER_AUTH": "",
  "ENTITLEMENT_SECRET": "etc-pki-entitlement",
  "HERMETIC": "true",
  "IMAGE": "quay.io/redhat-appstudio/ec-golden-image:530e8bd12585a3668f2af10454041738cb076883-amd64",
  "IMAGE_EXPIRES_AFTER": "",
  "PLATFORM": "linux/amd64",
  "PREFETCH_INPUT": "",
  "TARGET_STAGE": "",
  "TLSVERIFY": "true",
  "YUM_REPOS_D_FETCHED": "fetched.repos.d",
  "YUM_REPOS_D_SRC": "repos.d",
  "YUM_REPOS_D_TARGET": "/etc/yum.repos.d",
  "caTrustConfigMapKey": "ca-bundle.crt",
  "caTrustConfigMapName": "trusted-ca"
}
```

We may have to either make this Task specific, or type-specific (e.g. only look at values that look like a digest).

**Comment by zregvart** [comment]
I wonder if we could make an assumption that parameter values that are not emitted as results of any Task (or untrusted Tasks?) are defaults?
