### ISSUE TITLE
Audit the use of `lib.results_named`

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1081]
We're using `lib.results_named` liberally in policy rules, let's make sure that we don't take any Task result into consideration, but task results that originate from trusted tasks.
For example [fetching base images](https://github.com/enterprise-contract/ec-policies/blob/540adf985ae1432fc16129a7bc5676222da9d1c3/policy/release/base_image_registries.rego#L100C19-L100C36).

A/C:
* A list of places that use the lib.results_name helper.
* An analysis of security implications is done on each.
* Stories filed (or PRs created) for changes needed.

**Comment by lcarva** [comment]
I think for things like determining which base images were used, it's ok to _also_ use results from untrusted tasks because:

* There are other policy rules that verify a certain required task was included and it's trusted.
* If someone includes an untrusted task that emits the result of the same name, it doesn't loosen the check. If anything, it only makes it more strict.

**Comment by zregvart** [comment]
Kinda depends on what rules are included in the evaluation. I think a safer stance would be not to assume that another rule will check for untrusted tasks. Even more with trusted artifacts where it is permitted to add untrusted tasks which could lead to tricking the base image check.

**Comment by lcarva** [comment]
For context, that was the approach we used to have until we decided it was unnecessary and confusing to users: https://github.com/enterprise-contract/ec-policies/commit/34354313047b50851867cf1a270596ab6671f671

IMO, multiple concise policy rules that each perform a specific check should be our goal. It's not always possible though but it should be our default stance.

Auditing is good and we should do that from time to time. I just want us to be conscious of the trade-offs in coupling multiple requirements into single policy rules.

**Comment by joejstuart** [comment]
Is this something we need to audit from time to time or can we do anything to prevent having more audits? For example, renaming the function to `trusted_task_results` and another `non_trusted_task_results`, or maybe just adding some comments, etc.

**Comment by lcarva** [comment]
@joejstuart, that's a good point. I don't want us to have to introduce a periodic audit process. Maybe a counter to it is that since this hasn't been an issue yet, it's likely ok, mostly because of the required tasks rules. I don't know if this is a strong enough argument.

My hesitation with tying trusted Tasks to multiple policy rules is that it makes implementation and usage more complex.  We used to do this, and it was confusing to users. When a user had an old-enough Task, e.g. buildah,  which was then classified as an untrusted Task, the user would get multiple violations such as "required task not found" as well as "base images not found". Of course, we can clarify the error messages to be more specific, "base images not found in trusted tasks".

It's a balance between usability and security, which makes it hard to side against security...

**Comment by lcarva** [comment]
* Move away from the BASE_IMAGES_DIGESTS result.
  * Set a deprecation date on the v0.1 buildah Tasks. [STONEBLD-2678](https://issues.redhat.com/browse/STONEBLD-2678)
  * Update the policy rules to ignore the result after the v0.1 buildah Tasks have been deprecated. [EC-793](https://issues.redhat.com/browse/EC-793)
* Add a new policy rule in the task namespace to ensure the `clair-scan` Task from build-definitions specifies the expected result. [EC-794](https://issues.redhat.com/browse/EC-794)

I'm explicitly not filing an issue for the recommendation below:
* Add a new policy rule in the task namespace to ensure the test Tasks from build-definitions specifies the expected result. We could implement some sort of convention, e.g. a certain annotation, that identifies a Task as a test Task. A reason not to do that would be that, today, test Tasks are categorized by the test results they emit. Adding an annotation could be seen as unnecessary.
